import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class AlienAndGame
{
	public int getNumber(String[] board)
	{
		int i, j, n, m;
		int maxN;
		
		m = board.length;
		n = board[0].length();
		
		maxN = Math.min(m, n);
		
		while (maxN > 1) {
			if (areaPossible(board, m, n, maxN))
				return maxN * maxN;
			maxN--;
		}
		
		return 1;
		
	}
	
	public boolean areaPossible(String [] board, int m, int n, int N) {
	
		int i, j, p, q;
		int m1, n1;
		char color;
		boolean status = false;
		
	//	System.out.println("N = " + N);
		
		for (i = 0; i <= m - N; i++) {
		
			for (j = 0; j <= n - N; j++) {
			
				status = true;
				
		//		System.out.println("p = " + i + "; upto = " + (N + i) + "; q = " + j + "; upto = " + (N + j));
				
				for (p = i; p < N + i; p++) {
					
					color = board[p].charAt(j);
					
					for (q = j + 1; q < N + j; q++) {
					
						if (color != board[p].charAt(q)) {
							status = false;
							break;
						}
					
					}
					if (!status)
						break;	
				}
				
				if (status)
					return status;
			
			}
		}
	
		return status;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		AlienAndGame obj;
		int answer;
		obj = new AlienAndGame();
		long startTime = System.currentTimeMillis();
		answer = obj.getNumber(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		
		// ----- test 0 -----
		p0 = new String[]{"BB","WW"};
		p1 = 4;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"W"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"WBBB","WBBB","WWWW"};
		p1 = 9;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"W","B","W","W","W"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"BWBBWBB","WWBWWBW","BBBBBBW","WBBBBWB","BBWWWWB","WWWWWWW","BBWWBBB"};
		p1 = 9;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
