import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CirclesCountry
{
	public int leastBorders(int[] X, int[] Y, int[] R, int x1, int y1, int x2, int y2)
	{
		int i, j;
		int borders;
		double firstSign;
		double secondSign;
		
		borders = 0;
		
		for (i = 0; i < X.length; i++) {
		
			firstSign = (X[i] - x1) * (X[i] - x1)  + (Y[i] - y1) * (Y[i] - y1) - R[i] * R[i];
			secondSign = (X[i] - x2) * (X[i] - x2) + (Y[i] - y2) * (Y[i] - y2) - R[i] * R[i];
			
	//		System.out.println("firstSign = " + firstSign + "; secondSign = " + secondSign);
		
			if ((firstSign < 0.0 && secondSign > 0.0) || (firstSign > 0.0 && secondSign < 0.0))
				borders++;
		
		}
			
		return borders;
		
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int[] p2, int p3, int p4, int p5, int p6, boolean hasAnswer, int p7) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}" + "," + p3 + "," + p4 + "," + p5 + "," + p6);
		System.out.println("]");
		CirclesCountry obj;
		int answer;
		obj = new CirclesCountry();
		long startTime = System.currentTimeMillis();
		answer = obj.leastBorders(p0, p1, p2, p3, p4, p5, p6);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p7);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p7;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		int[] p2;
		int p3;
		int p4;
		int p5;
		int p6;
		int p7;
		
		// ----- test 0 -----
		p0 = new int[]{0};
		p1 = new int[]{0};
		p2 = new int[]{2};
		p3 = -5;
		p4 = 1;
		p5 = 5;
		p6 = 1;
		p7 = 0;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, p5, p6, true, p7) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{0,-6,6};
		p1 = new int[]{0,1,2};
		p2 = new int[]{2,2,2};
		p3 = -5;
		p4 = 1;
		p5 = 5;
		p6 = 1;
		p7 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, p5, p6, true, p7) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{1,-3,2,5,-4,12,12};
		p1 = new int[]{1,-1,2,5,5,1,1};
		p2 = new int[]{8,1,2,1,1,1,2};
		p3 = -5;
		p4 = 1;
		p5 = 12;
		p6 = 1;
		p7 = 3;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, p5, p6, true, p7) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{-3,2,2,0,-4,12,12,12};
		p1 = new int[]{-1,2,3,1,5,1,1,1};
		p2 = new int[]{1,3,1,7,1,1,2,3};
		p3 = 2;
		p4 = 3;
		p5 = 13;
		p6 = 2;
		p7 = 5;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, p5, p6, true, p7) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{-107,-38,140,148,-198,172,-179,148,176,153,-56,-187};
		p1 = new int[]{175,-115,23,-2,-49,-151,-52,42,0,68,109,-174};
		p2 = new int[]{135,42,70,39,89,39,43,150,10,120,16,8};
		p3 = 102;
		p4 = 16;
		p5 = 19;
		p6 = -108;
		p7 = 3;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, p5, p6, true, p7) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
