import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class DVDPlayer
{
	public String[] findMovies(String[] moviesWatched)
	{
		int i;
		int N;
		String value;
		ArrayList<String> ans;
		HashMap<String, String> movie1;
		HashSet<String> movie2;
		StringTokenizer st;
		
		ans = new ArrayList<String>();
		movie1 = new HashMap<String, String>();
		movie2 = new HashSet<String>();
		
		N = moviesWatched.length;
		
		movie1.put(moviesWatched[0], moviesWatched[1]);
		movie1.put(moviesWatched[1], null);
				
		for (i = 0; i < N - 1; i++) {
			value = moviesWatched[i + 1];
			if (movie1.containsKey(moviesWatched[i + 1]) && movie1.get(moviesWatched[i + 1]) != null) {
				value = movie1.get(moviesWatched[i + 1]);
			}
			movie1.put(moviesWatched[i], value);
			movie1.put(moviesWatched[i + 1], null);
		}
		movie1.remove(moviesWatched[i]);
		
		Set<String> keys = movie1.keySet();
		
		for (String key: keys) {
		//	System.out.print(key + ": ");
		//	System.out.println(movie1.get(key));
			
			if (key.equals(movie1.get(key)))
				continue;
			ans.add(key + " is inside " + movie1.get(key) + "'s case");
		}
		
		Collections.sort(ans);
		
		return ans.toArray(new String[ans.size()]);
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		DVDPlayer obj;
		String[] answer;
		obj = new DVDPlayer();
		long startTime = System.currentTimeMillis();
		answer = obj.findMovies(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		
		// ----- test 0 -----
		p0 = new String[]{"citizenkane","casablanca","thegodfather"};
		p1 = new String[]{"casablanca is inside thegodfather's case","citizenkane is inside casablanca's case"};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"starwars","empirestrikesback","returnofthejedi","empirestrikesback","returnofthejedi","phantommenace","starwars"};
		p1 = new String[]{"empirestrikesback is inside returnofthejedi's case","phantommenace is inside empirestrikesback's case","returnofthejedi is inside phantommenace's case"};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"a","x","a","y","a","z","a"};
		p1 = new String[]{};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
