import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class EelAndRabbit
{
	public int getmax(int[] l, int[] t)
	{
		int i;
		int j;
		int max = 0;
		int ans[];
		int temp = 0;
		
		int time[] = (int []) t.clone();
		
		Arrays.sort(time);
		
		if (t.length > 1)
			max = time[t.length - 1] + time[t.length - 2];
		else
			max = time[t.length - 1];
			
		ans = new int[max + 1];
		
		for (i = 0; i < max; i++) {
			for (j = 0; j < l.length; j++) {
				if (i - t[j] == 0)
					ans[i]++;
				else if (i - t[j] > 0 && i - t[j] - l[j] <= 0)
					ans[i]++;				
			}
			System.out.println("ans[" + i + "] = " + ans[i]);
		}
		
		Arrays.sort(ans);
		
		return (ans[max -1] + ans[max]);
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}");
		System.out.println("]");
		EelAndRabbit obj;
		int answer;
		obj = new EelAndRabbit();
		long startTime = System.currentTimeMillis();
		answer = obj.getmax(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new int[]{2,4,3,2,2,1,10};
		p1 = new int[]{2,6,3,7,0,2,0};
		p2 = 6;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{1,1,1};
		p1 = new int[]{2,0,4};
		p2 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{1};
		p1 = new int[]{1};
		p2 = 1;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{8,2,1,10,8,6,3,1,2,5};
		p1 = new int[]{17,27,26,11,1,27,23,12,11,13};
		p2 = 7;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
