import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FormatAmt
{
	public String amount(int dollars, int cents)
	{
		char [] Dollars;
		char[] Cents;
		String amount = "";
		int temp;
		
		Dollars =  String.valueOf(dollars).toCharArray();
		Cents = String.valueOf(cents).toCharArray();
		
		temp = Dollars.length - 1;
		for (int i = Dollars.length - 1; i >= 0; i--) {
			if (temp - i == 3) {
				amount = "," + amount;
				temp = i;
			}
			amount = Dollars[i] + amount;
		}
		if (Cents.length == 1)
			amount = "$" + amount + ".0" + String.valueOf(Cents);
		else
			amount = "$" + amount + "." + String.valueOf(Cents);		
		return amount;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
		System.out.println("]");
		FormatAmt obj;
		String answer;
		obj = new FormatAmt();
		long startTime = System.currentTimeMillis();
		answer = obj.amount(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		String p2;
		
		// ----- test 0 -----
		p0 = 123456;
		p1 = 0;
		p2 = "$123,456.00";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 49734321;
		p1 = 9;
		p2 = "$49,734,321.09";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 0;
		p1 = 99;
		p2 = "$0.99";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 249;
		p1 = 30;
		p2 = "$249.30";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 1000;
		p1 = 1;
		p2 = "$1,000.01";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
