import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FoxAndFencingEasy
{
	public String WhoCanWin(int mov1, int mov2, int d)
	{
		int i;
		int j;
		
		if ( mov1 >= d )
			return "Ciel";
			
		if (mov1 == mov2)
			return "Draw";
			
		
		if (mov1 < mov2) {
		
			if (mov2 - mov1 > mov1)
				return "Liss";
		
		}
		else if (mov1 > mov2) {
		
			if (mov1 - mov2 > mov2)
				return "Ciel";
		
		}
		
			
		return "Draw";
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, boolean hasAnswer, String p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2);
		System.out.println("]");
		FoxAndFencingEasy obj;
		String answer;
		obj = new FoxAndFencingEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.WhoCanWin(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p3 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p3);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int p2;
		String p3;
		
		// ----- test 0 -----
		p0 = 1;
		p1 = 58;
		p2 = 1;
		p3 = "Ciel";
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 100;
		p1 = 100;
		p2 = 100000000;
		p3 = "Draw";
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 100;
		p1 = 150;
		p2 = 100000000;
		p3 = "Draw";
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 100;
		p1 = 250;
		p2 = 100000000;
		p3 = "Liss";
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
