import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class HandsShaking
{
	public long countPerfect(int n)
	{
		int i;
		int j;
		int N;
		long catalan[];
		
		N = n / 2;
		
		catalan = new long[N + 1];
		
		catalan[0] = 1;
//		catalan[1] = 1;
		
		for (i = 1; i <= N; i++) {
		
			for (j = 0; j < i; j++) {
			
				catalan[i] += (catalan[j] * catalan[i - j - 1]);
				
		//		System.out.println("catalan[" + j + "] = " + catalan[j] + ", catalan[" + (i - j - 1) + "] = " + catalan[i -j - 1]);
			
			}
		}
		
//		for (i = 0; i <= N; i++)
//			System.out.print(catalan[i] + ", ");
		
		return catalan[N];
				
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, boolean hasAnswer, long p1) {
		System.out.print("Test " + testNum + ": [" + p0);
		System.out.println("]");
		HandsShaking obj;
		long answer;
		obj = new HandsShaking();
		long startTime = System.currentTimeMillis();
		answer = obj.countPerfect(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		long p1;
		
		// ----- test 0 -----
		p0 = 2;
		p1 = 1L;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 4;
		p1 = 2L;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 8;
		p1 = 14L;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
