import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ICPCBalloons
{

	private class Balloon implements Comparable<Balloon>{
	
		public int count;
		public char size;
		
		public Balloon(int c, char s) {
			count = c;
			size = s;
		}
		
		@Override
		public int compareTo(Balloon b) {
		
			if (this.count - b.count > 0)
				return -1;
			else if (this.count - b.count < 0)
				return 1;
			else
				return 0;
		
		}
	
	}

	public int minRepaintings(int[] balloonCount, String balloonSize, int[] maxAccepted)
	{
		int i;
		int j;
		int N;
		int sumM;
		int sumL;
		int repaint;
		char size;
		
		N = balloonCount.length;
		
		Balloon balloon[] = new Balloon[N];
		
		sumM = 0;
		sumL = 0;
		
		for (i = 0; i < N; i++) {
		
			balloon[i] = new Balloon(balloonCount[i], balloonSize.charAt(i));
			
			if (balloonSize.charAt(i) == 'L')
				sumL += balloonCount[i];
			else
				sumM += balloonCount[i];
		
		}
		
		Arrays.sort(balloon);
		
		for (i = 0; i < N; i++) {
		
		//	System.out.println(balloon[i].count + " " + balloon[i].size);
				
		}
		
		repaint = 0;
		
		for (i = 0; i < maxAccepted.length; i++) {
		
			for (j = 0; j < N; j++) {
			
				
			
			}
			
		
		}
		
		
		return -1;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, String p1, int[] p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "\"" + p1 + "\"" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}");
		System.out.println("]");
		ICPCBalloons obj;
		int answer;
		obj = new ICPCBalloons();
		long startTime = System.currentTimeMillis();
		answer = obj.minRepaintings(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		String p1;
		int[] p2;
		int p3;
		
		// ----- test 0 -----
		p0 = new int[]{100};
		p1 = "L";
		p2 = new int[]{1,2,3,4,5};
		p3 = 10;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{100};
		p1 = "M";
		p2 = new int[]{10,20,30,40,50};
		p3 = -1;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{5,6,1,5,6,1,5,6,1};
		p1 = "MLMMLMMLM";
		p2 = new int[]{7,7,4,4,7,7};
		p3 = 6;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{100,100};
		p1 = "ML";
		p2 = new int[]{50,51,51};
		p3 = -1;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{8,5,1,4,1,1,3,1,3,3,5,4,5,6,9};
		p1 = "MMMLLLMMLLMLMLM";
		p2 = new int[]{3,5,3,3,5,6,4,6,4,2,3,7,1,5,2};
		p3 = 5;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new int[]{1,18,4,7,19,7,7,1,4,8,10,5,14,13,8,22,6,3,13,5,3,4,2,1,3,15,19,4,5,9,4,11,2,7,12,20,11,26,22,7,2,10,9,20,13,20,2,9,11,9};
		p1 = "LLMLLLLMLLLLLLLLLLLLMLLLLLLLLLLMMLMLLLMLLLLLLLLMLL";
		p2 = new int[]{44,59,29,53,16,23,13,14,29,42,13,15,66,4,47};
		p3 = 210;
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
