import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ORSolitaireDiv2
{
	public int getMinimum(int[] numbers, int goal)
	{
		int i;
		int j;
		int k;
		int N;
		int gTemp;
		int bits[] = new int[32];
		
		N = numbers.length;
		
		int min = Integer.MAX_VALUE;
		
		gTemp = goal;
		int temp = 0;
		
		for (j = 0; gTemp > 0; j++) {
		
			if ((gTemp & 1) == 1) {
				bits[j] = 1;			
			}
			
			gTemp = gTemp >> 1;
		
		}
		
		for (i = 0; i < 32; i++) {

	//		System.out.println("bits[" + i + "]: " + bits[i]);
			
			temp = 0;
			
			if (bits[i] == 0)
				continue;
		
			for (j = 0; j < N; j++) {
			
				if (((goal | numbers[j]) == goal) && ((numbers[j] & (bits[i] << i)) != 0))
					temp++;	
			
			}
			
			min = Math.min(min, temp);
		}
				
		return min;
		
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		ORSolitaireDiv2 obj;
		int answer;
		obj = new ORSolitaireDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.getMinimum(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new int[]{1,2,4};
		p1 = 7;
		p2 = 1;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{1,2,4,7,8};
		p1 = 7;
		p2 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{12571295,2174218,2015120};
		p1 = 1;
		p2 = 0;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{5,2,4,52,62,9,8,3,1,11,6};
		p1 = 11;
		p2 = 3;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{503,505,152,435,491,512,1023,355,510,500,502,255,63,508,509,511,60,250,254,346};
		p1 = 510;
		p2 = 5;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
