import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class Salary
{
	public final int TIME_EVE = 18 * 3600;
	public final int TIME_MORN = 5 * 3600 + 59 * 60 + 59;
	public int howMuch(String[] arrival, String[] departure, int wage)
	{
		int i;
		int arrivals[] = new int[arrival.length];
		int departures[] = new int[departure.length];
		String aTmp[];
		String dTmp[];
		int aTimeSec;
		int dTimeSec;
		double mul = 1.5;
		double totalWage = 0;
		
		for (i = 0; i < arrival.length; i++) {
			aTimeSec = 0;
			dTimeSec = 0;
			aTmp = arrival[i].split(":");
			dTmp = departure[i].split(":");
			for (int j = 0; j < 3; j++) {
				aTimeSec = aTimeSec * 60 + Integer.valueOf(aTmp[j]);
				dTimeSec = dTimeSec * 60 + Integer.valueOf(dTmp[j]);
			}
			arrivals[i] = aTimeSec;
			departures[i] = dTimeSec;
			
			System.out.println(arrivals[i] + "\t" + departures[i]);
		}
		
		for (i = 0; i < arrival.length; i++) {
			if (arrivals[i] < TIME_MORN) {
				if (departures[i] <= TIME_MORN) {
					totalWage += mul * wage * (departures[i] - arrivals[i]);
				}
				else if (departures[i] <= TIME_EVE) {
					totalWage += mul * wage * (TIME_MORN - arrivals[i]) + wage * (departures[i] - TIME_MORN);
				}
				else {
					totalWage += mul * wage * (TIME_MORN - arrivals[i]) + wage * (TIME_EVE - TIME_MORN) + mul * wage * (departures[i] - TIME_EVE);
				}			
			}
			else if (arrivals[i] < TIME_EVE) {
				if (departures[i] <= TIME_EVE) {
					totalWage += wage * (departures[i] - arrivals[i]);
				}
				else
					totalWage += wage * (TIME_EVE - arrivals[i]) + mul * wage * (departures[i] - TIME_EVE);
			}
			else {
				totalWage += mul * wage * (departures[i] - arrivals[i]);
			}
			
		}
		
		totalWage /= 3600;
		System.out.println("Total Wage = " + totalWage);
		
		return ((int)totalWage);
	}
		// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, int p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}" + "," + p2);
		System.out.println("]");
		Salary obj;
		int answer;
		obj = new Salary();
		long startTime = System.currentTimeMillis();
		answer = obj.howMuch(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		int p2;
		int p3;
		
		// ----- test 0 -----
		p0 = new String[]{"08:00:00","13:00:00","19:27:32"};
		p1 = new String[]{"12:00:00","17:00:00","20:48:10"};
		p2 = 1000;
		p3 = 10015;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"01:05:47","16:48:12"};
		p1 = new String[]{"09:27:30","21:17:59"};
		p2 = 2000;
		p3 = 33920;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"00:00:00"};
		p1 = new String[]{"23:59:59"};
		p2 = 10000;
		p3 = 299995;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"10:00:00"};
		p1 = new String[]{"18:00:00"};
		p2 = 10000;
		p3 = 80000;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"22:19:46"};
		p1 = new String[]{"23:12:46"};
		p2 = 5320;
		p3 = 7049;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING

}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
