import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class Snowflakes
{
	public String[] flareOut(String[] snowflake)
	{
		int i;
		int j;
		int N;
		int n;
		String square[];
		
		n = snowflake.length;
		N = 2 * n; // Number of points
		
		square = new String[N];
		
		for (i = 0; i < n; i++) {
		
			for (j = i + 1; j < n; j++) {
			
				snowflake[i] = snowflake[i] + snowflake[j].charAt(i);
			
			}
		}
		
		for (i = 0; i < n; i++) {
			square[n + i] = reverse(snowflake[i].substring(0, n)) + snowflake[i];
		}
		
		for (i = 0; i < n; i++) {
			square[i] = square[N - 1 - i];
		//	square[i] = new String();
		}
		
		
		return square;
		
	}
	
	public String reverse(String str) {
	
		int i;
		char [] s;
		int N;
		
		N = str.length();
		s = new char[N];
		
		for (i = 0; i < N; i++)
			s[i] = str.charAt(N - 1 - i);
			
		return new String(s);
	
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		Snowflakes obj;
		String[] answer;
		obj = new Snowflakes();
		long startTime = System.currentTimeMillis();
		answer = obj.flareOut(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		
		// ----- test 0 -----
		p0 = new String[]{".","..","*.*"};
		p1 = new String[]{"*.**.*","......","*....*","*....*","......","*.**.*"};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"*","..",".*.",".**.",".*.**"};
		p1 = new String[]{"**.*..*.**","*.**..**.*",".*.*..*.*.","***....***","....**....","....**....","***....***",".*.*..*.*.","*.**..**.*","**.*..*.**"};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{".","..","***"};
		p1 = new String[]{"******","*....*","*....*","*....*","*....*","******"};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"*",".*","***"};
		p1 = new String[]{"******","**..**","*.**.*","*.**.*","**..**","******"};
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{".","..","***","...."};
		p1 = new String[]{"........",".******.",".*....*.",".*....*.",".*....*.",".*....*.",".******.","........"};
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
