import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class TheDeviceDiv2
{
	public String identify(String[] plates)
	{
		int i, j;
		int M, N;
		boolean bitResult;
		int bitOne;
		int bitZero;
		
		M = plates.length;
		N = plates[0].length();
		
//		bitResult = new boolean[N];
		bitResult = true;
		
		if (M == 1)
			return "NO";
			
		for (i = 0; i < N; i++) {
		
			bitOne = 0;
			bitZero = 0;
		
			for (j = 0; j < M; j++) {
				
				if (plates[j].charAt(i) == '0')
					bitZero++;
					
				else
					bitOne++;
			
			}
			
			if (!(bitZero >= 1 && bitOne >= 2)) {
				bitResult = false;
				break;
			}
		}
		
		if (bitResult)
			return "YES";
		
		return "NO";
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		TheDeviceDiv2 obj;
		String answer;
		obj = new TheDeviceDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.identify(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		
		// ----- test 0 -----
		p0 = new String[]{"010","011","000"};
		p1 = "NO";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"1","0","1","0"};
		p1 = "YES";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"11111"};
		p1 = "NO";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"0110011","0101001","1111010","1010010"};
		p1 = "NO";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"101001011","011011010","010110010","111010100","111111111"};
		p1 = "YES";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
