import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class VolumeGuess
{
	public int correctVolume(String[] queries, int numberOfBoxes, int ithBox)
	{
		int ret = 0;
		for (int i=0; i<queries.length; i++)
		{
			int[] info = splitInts(queries[i]);
			if (info[0] == ithBox || info[1] == ithBox)
				ret = Math.max(ret, info[2]);
		}
		return ret;
	}
	
	int[] splitInts(String s)
	{
		String[] split = s.split("[ ,]+");
		int[] ret = new int[split.length];
		for (int i=0; i<ret.length; i++)
			ret[i] = Integer.parseInt(split[i]);
		return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, int p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1 + "," + p2);
		System.out.println("]");
		VolumeGuess obj;
		int answer;
		obj = new VolumeGuess();
		long startTime = System.currentTimeMillis();
		answer = obj.correctVolume(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		int p2;
		int p3;
		
		// ----- test 0 -----
		p0 = new String[]{"1,2,10","1,3,10","2,3,20"};
		p1 = 3;
		p2 = 1;
		p3 = 10;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"1,02,10","2,3,010","1,3,20"};
		p1 = 3;
		p2 = 2;
		p3 = 10;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"1,2,31","1,3,9","1,4,31","2,4,32","3,4,9","3,2,9"};
		p1 = 4;
		p2 = 1;
		p3 = 31;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"1,2,31","1,3,9","1,4,31","2,4,32","3,4,9","3,2,9"};
		p1 = 4;
		p2 = 3;
		p3 = 9;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
